sonar.projectKey=FreeCastInc_SelectTVReact
sonar.organization=freecastinc
sonar.host.url=https://sonarcloud.io
sonar.projectName=SelectTVReact
sonar.sources=./src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.test.*,src/test_utils/*
sonar.coverage.exclusions=src/**/__mocks__/**,src/**/*.test.*
sonar.test.exclusions=src/**/__mocks__/**,src/**/*.test.*
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S3358
sonar.issue.ignore.multicriteria.e1.resourceKey=.
