[tox]
envlist =
    linting
    py
skipsdist = True
toxworkdir = src/

[docker:db]
image = mysql:8
volumes =
    bind:rw:{toxinidir}/provision/create_test_db.sql:/docker-entrypoint-initdb.d/1.sql
    bind:rw:{toxinidir}/provision/test_stv.sql:/docker-entrypoint-initdb.d/2.sql
    bind:rw:{toxinidir}/provision/test_rtv2.sql:/docker-entrypoint-initdb.d/3.sql
environment =
    MYSQL_ALLOW_EMPTY_PASSWORD=1
# The healthcheck ensures that tox-docker won't run tests until the
# container is up and the command finishes with exit code 0 (success)
healthcheck_cmd = mysql -uroot -D test_rtv2 -e "SELECT 1 FROM youlive_stationfilelog;"
healthcheck_interval = 5
healthcheck_timeout = 500
healthcheck_retries = 100
healthcheck_start_period = 20
ports = 3306:3306/tcp

[testenv:py]
deps = -rrequirements_test.txt
setenv =
    ENVIRONMENT = test
commands =
    coverage run -m pytest {posargs}
    coverage xml
docker =
    db

[coverage:run]
relative_files = True
source = src/
branch = True

[flake8]
max-line-length = 120
extend-ignore =
    ; whitespace before ':'
    E203
    ; Missing Docstrings
    D100,D101,D102,D103,D104,D105,D106,D107
    ; Whitespace Issues
    D202,D203,D204,D205,D209,D213
    ; Quotes Issues
    D302
    ; Docstring Content Issues
    D400,D401,D401,D402,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,D415,D416,D417

[testenv:linting]
deps = pre-commit>=2.9.3
commands = pre-commit run --show-diff-on-failure

[isort]
; This config mimics what reorder-python-imports does.
force_single_line = 1
known_localfolder = pytest,_pytest
known_third_party = test_source,test_excinfo
force_alphabetical_sort_within_sections = 1
