name: Get openapi file

# on:
#   workflow_dispatch:

on:
  workflow_run:
    workflows: [Testing FC_fastapi]
    types:
      - completed 

jobs:
  test1:   
    runs-on: ubuntu-latest
    steps:  
      - name: Show checkout files
        run: |
          echo 'Get openapi file'