name: SonarCloud Scan2
on:
  push:
    branches:
      - master
      - testing
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud Trigger2
    runs-on: self-hosted
    container: node:16.14.0
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - run: sleep 3m    
      # - name: Make a change to trigger the pipeline
      #   run: |
      #     echo 'Dummy change number 1'
      #     echo "USER:USER GITHUB_WORKSPACE:$RUNNER_NAME"
      #     echo "$USER:$USER $GITHUB_WORKSPACE:$RUNNER_NAME"
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}          
      # - name: Install dependencies
      #   run: npm ci
      # - name: Test and coverage
      #   run: CI=true npm run test -- --coverage
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

