name: Testing FC_fastapi

# on:
#   workflow_dispatch:

on:
  workflow_run:
    workflows:
      - Dev deployment
    types:
      - completed

jobs:
  test1:   
    runs-on: ubuntu-latest
    steps:  
      - name: Show checkout files
        run: |
          echo 'Deployment'