name: Testing FC_fastapi

# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - develop

jobs:
  test1:   
    runs-on: ubuntu-latest
    steps:  
      - name: Show checkout files
        run: |
          echo 'Deployment'