name: Deploy.

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy in test stage
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Deploying in test stage"
