name: Dev deployment

on:
  push:
    branches:
      - common

jobs:
  test1:   
    runs-on: ubuntu-latest
    steps:  
      - name: Show checkout files
        run: |
          echo 'Get openapi file'
