name: Deploy.

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy in ${{ needs.map-envs.outputs.stage }} stage
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Deploying in ${{ needs.map-envs.outputs.stage }} stage"
