name: "Remove resource from Terraform State File. Forget about the resource"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'dryRun'
        type: choice
        options:
        - true
        - false
        default: 'true'    
      resourceAddress:
        type: string
        description: 'Terraform resource address'
        required: true
        default: ''

jobs:
  terraform_state_rm:
    name: "terraform state removal"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.1.4
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      #   if: ${{ github.event.inputs.dryRun == 'true' }}

      - name: Dry Terraform Apply Refresh
        id: DryApplyRefresh
        run: echo 'terraform -chdir=dev state rm ${{ github.event.inputs.resourceAddress }}'
        if: ${{ github.event.inputs.dryRun == 'true' }}          
          
      - name: Terraform Apply Refresh
        id: ApplyRefresh
        run: echo 'terraform -chdir=dev state rm ${{ github.event.inputs.resourceAddress }}'
        if: ${{ github.event.inputs.dryRun == 'false' }}