name: Merge development into staging branch
on: workflow_dispatch
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: DISPLAY SECRETS
        run: |
          echo "TEST_USER_USERNAME"
          echo ${{secrets.TEST_USER_USERNAME}} | sed 's/./& /g'

          echo "TEST_USER_PASSWORD"
          echo ${{secrets.TEST_USER_PASSWORD}} | sed 's/./& /g'

          echo "TEST_FREE_USER_USERNAME"
          echo ${{secrets.TEST_FREE_USER_USERNAME}} | sed 's/./& /g'

          echo "TEST_FREE_USER_PASSWORD"
          echo ${{secrets.TEST_FREE_USER_PASSWORD}} | sed 's/./& /g'

          echo "TEST_SUBSCRIBED_USER_USERNAME"
          echo ${{secrets.TEST_SUBSCRIBED_USER_USERNAME}} | sed 's/./& /g'

          echo "TEST_BRAND_SLUG"
          echo ${{secrets.TEST_BRAND_SLUG}} | sed 's/./& /g'

          echo "TEST_DEFAULT_PLATFORM"
          echo ${{secrets.TEST_DEFAULT_PLATFORM}} | sed 's/./& /g'

          echo "TEST_SHOW_SLUG"
          echo ${{secrets.TEST_SHOW_SLUG}} | sed 's/./& /g'
