name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:    
      group: ubuntu-runners
      labels: ${{ vars.RUNS_ON_GROUP}}    
    #runs-on: ${{ vars.RUNS_ON_LABEL}}
    steps:
      - run: "echo Test"