name: Run a command on the self-hosted runner.
on: 
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  # Job to 
  determine-runner:
    runs-on: self-hosted
    steps:
      - name: Run command
        run: echo "Running on self-hosted runner"
   